import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

df = pd.read_excel('data/B01 NCV Data.xlsx')
df = df.rename(columns={'EMG 17 (mV)': 'EMG 17', 'EMG 20 (mV)': 'EMG 20', 'Stim (20)': 'Stim 20',
               'EMG 25 (mV)': 'EMG 25', 'EMG 29 (mV)': 'EMG 29'})
# Find stimulation pulse and resultant M-waves at each stimulation intensity
# Plot stimulation and EMG channels on separate Y axes
# M-waves = the M-wave represents the activity generated by individual muscle fibres
## innervated by the stimulated motor axons. The response is measured as the EMG activity
## (M-wave) or force associated with the response. The shape and size of the M-wave
## depends on the number and size of activated muscle fibres as well as temporal dispersion
## of their action potentials. Some M-waves may be preceded by a small potential that
## should be discarded in determining motor latencies.
# STIMULATION PULSE = Voltage
# RESULTANT M-Wave = EMG signal
plt.plot(df['EMG 17'])
plt.show()
plt.plot(df['Stim 17'])
plt.show()
